:name: Keys Source Connector
[[_source_keys]]
= {name}

The {name} captures changes happening to keys in a Redis database and publishes keys and values to a Kafka topic.
The data structure key will be mapped to the record key, and the value will be mapped to the record value.

**Make sure the Redis database has keyspace notifications enabled** using `notify-keyspace-events = KEA` in `redis.conf` or via `CONFIG SET`.
For more details see {link_redis_notif}.

[[_source_keys_class]]
== Class Name

The {name} class name is `com.redis.kafka.connect.RedisKeysSourceConnector`.

The corresponding configuration property would be:

[source,properties]
----
connector.class = com.redis.kafka.connect.RedisKeysSourceConnector
----

[[_source_keys_delivery]]
== Delivery Guarantees

The {name} does not guarantee data consistency because it relies on Redis keyspace notifications which have no delivery guarantees.
It is possible for some notifications to be missed, for example in case of network failures.

Also, depending on the type, size, and rate of change of data structures on the source it is possible the connector cannot keep up with the change stream.
For example if a big set is repeatedly updated the connector will need to read the whole set on each update and transfer it over to the target database.
With a big-enough set the connector could fall behind and the internal queue could fill up leading up to updates being dropped.
Some preliminary sizing using Redis statistics and `bigkeys`/`memkeys` is recommended.
If you need assistance please contact your Redis account team.

[[_source_keys_tasks]]
== Tasks

The {name} should only be configured with one task as keyspace notifications are broadcast to all listeners and cannot be consumed in a round-robin fashion.

[[_source_keys_redis_client]]
include::{includedir}/_redis_client.adoc[leveloffset=+1]


[[_source_keys_config]]
== Configuration
[source,properties]
----
connector.class    = com.redis.kafka.connect.RedisKeysSourceConnector
redis.keys.pattern = <glob> <1>
redis.keys.timeout = <millis> <2>
topic              = <name> <3>
----
<1> Key pattern to subscribe to.
This is the key portion of the pattern that will be used to listen to keyspace events.
For example `foo:*` translates to pubsub channel `$$__$$keyspace@0$$__$$:foo:*` and will capture changes to keys `foo:1`, `foo:2`, etc.
See {link_redis_keys} for pattern details.
<2> Idle timeout in millis.
Duration after which the connector will stop if no activity is encountered.
<3> Name of the destination topic.

