import org.gradle.api.plugins.jvm.JvmTestSuite
import org.springframework.boot.gradle.plugin.SpringBootPlugin

plugins {
    id 'java-library'
    alias(libs.plugins.spring.boot) apply false
    alias(libs.plugins.spring.dependency.management) apply false
    alias(libs.plugins.axion.release)
    alias(libs.plugins.ben.manes.versions)
    alias(libs.plugins.shadow) apply false
}

group = 'com.redis'

scmVersion {
    tag {
        prefix = 'v'
        versionSeparator = ''
    }
}

version = scmVersion.version

ext['lettuce.version'] = libs.versions.lettuce.get()
ext['netty.version'] = libs.versions.netty.get()

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'io.spring.dependency-management'

    group = rootProject.group
    version = rootProject.version

    repositories {
        mavenCentral()
    }

    dependencyManagement {
        imports {
            mavenBom SpringBootPlugin.BOM_COORDINATES
        }
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    tasks.register('sourcesJar', Jar) {
        archiveClassifier.set('sources')
        from sourceSets.main.allSource
    }

    tasks.register('javadocJar', Jar) {
        dependsOn javadoc
        archiveClassifier.set('javadoc')
        from javadoc.destinationDir
    }

    build {
        dependsOn sourcesJar, javadocJar
    }

    testing {
        suites {
            test {
                useJUnitJupiter()
            }

            integrationTest(JvmTestSuite) {
                useJUnitJupiter()

                dependencies {
                    implementation project()
                    implementation 'org.junit.jupiter:junit-jupiter'
                    implementation 'org.assertj:assertj-core'
                    runtimeOnly 'org.junit.platform:junit-platform-launcher'
                }

                targets {
                    all {
                        testTask.configure {
                            shouldRunAfter(test)
                        }
                    }
                }
            }
        }
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
        testLogging {
            events 'passed', 'skipped', 'failed'
            exceptionFormat = 'full'
        }
        systemProperty 'io.lettuce.core.epoll', 'false'
        systemProperty 'io.lettuce.core.kqueue', 'false'
        systemProperty 'io.lettuce.core.iouring', 'false'
    }

    tasks.named('check') {
        dependsOn tasks.named('integrationTest')
    }

    dependencies {
        testImplementation 'org.junit.jupiter:junit-jupiter'
        testImplementation 'org.assertj:assertj-core'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }
}

subprojects {
    apply plugin: 'maven-publish'

    publishing {
        publications {
            mavenJava(MavenPublication) {
                from components.java
                artifact javadocJar
                artifact sourcesJar
                groupId = project.group
                artifactId = project.name
                version = project.version

                versionMapping {
                    usage('java-api') {
                        fromResolutionOf('runtimeClasspath')
                    }
                    usage('java-runtime') {
                        fromResolutionResult()
                    }
                }

                pom {
                    packaging = 'jar'
                    name = project.name
                    description.set(project.provider { project.description ?: project.name })
                    url = 'https://github.com/redis-field-engineering/redis-kafka-connect'
                    inceptionYear = '2021'

                    licenses {
                        license {
                            name = 'The Apache License, Version 2.0'
                            url = 'https://www.apache.org/licenses/LICENSE-2.0'
                        }
                    }

                    developers {
                        developer {
                            id = 'jruaux'
                            name = 'Julien Ruaux'
                            email = 'julien@redis.com'
                        }
                    }

                    scm {
                        connection = 'scm:git:git://github.com/redis-field-engineering/redis-kafka-connect.git'
                        developerConnection = 'scm:git:ssh://github.com:redis-field-engineering/redis-kafka-connect.git'
                        url = 'https://github.com/redis-field-engineering/redis-kafka-connect'
                    }
                }
            }
        }

        repositories {
            maven {
                url = rootProject.layout.buildDirectory.dir('staging-deploy')
            }
        }
    }
}
