plugins {
    id 'java-library'
    alias(libs.plugins.shadow)
}

description = 'Redis Kafka Connect'

dependencies {
    implementation libs.lettucemod
    implementation libs.spring.batch.redis.core
    implementation 'org.apache.commons:commons-pool2'
    implementation 'org.slf4j:slf4j-api'
    compileOnly 'org.apache.kafka:connect-api'
    compileOnly 'org.apache.kafka:connect-json'
    testImplementation 'org.apache.kafka:connect-api'
    testImplementation 'org.apache.kafka:connect-json'
    testImplementation 'org.awaitility:awaitility'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
    testImplementation 'org.junit.jupiter:junit-jupiter-params'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine'
    testImplementation 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.slf4j:slf4j-simple'
    testImplementation libs.spring.batch.redis.test
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation libs.testcontainers.redis
    testImplementation libs.testcontainers.redis.enterprise
    integrationTestImplementation libs.spring.batch.redis.test
    integrationTestImplementation 'org.mockito:mockito-core'
    integrationTestImplementation 'org.apache.kafka:connect-api'
    integrationTestImplementation 'org.apache.kafka:connect-json'
    integrationTestImplementation 'org.testcontainers:junit-jupiter'
    integrationTestImplementation libs.testcontainers.redis
    integrationTestImplementation libs.testcontainers.redis.enterprise
    integrationTestImplementation 'org.awaitility:awaitility'
    integrationTestRuntimeOnly 'org.slf4j:slf4j-simple'
}

testing {
    suites {
        integrationTest {
            sources {
                java {
                    srcDirs = ['src/test/java']
                }
                resources {
                    srcDirs = ['src/test/resources']
                }
            }
        }
    }
}

tasks.named('test') {
    exclude '**/*IntegrationTests.class'
    exclude '**/Abstract*IntegrationTests.class'
    exclude '**/RedisContainerFactory.class'
}

tasks.named('integrationTest') {
    include '**/*IntegrationTests.class'
}

jar.finalizedBy shadowJar

tasks.named('shadowJar') {
    mergeServiceFiles()
}

String archiveFilename = 'redis-redis-kafka-connect'
String releaseDate = java.time.format.DateTimeFormatter.ISO_LOCAL_DATE.format(java.time.LocalDateTime.now())

tasks.register('prepareConfluentArchive', Copy) {
    group = "Confluent"
    description = "Prepares the Confluent archive file for Confluent Hub"
    dependsOn tasks.shadowJar
    
    String baseDir = "$archiveFilename-${project.version}"
    from('config/archive/manifest.json') {
        expand(projectVersion: "${project.version}", releaseDate: "${releaseDate}")
    }
    from('config/archive/assets') {
        into 'assets'
    }
    from(layout.buildDirectory.dir('libs')) {
        include "${project.name}-${project.version}-all.jar"
        into 'lib'
    }
    from('../..') {
        include 'README.adoc'
        include 'LICENSE'
        into 'doc'
    }
    into layout.buildDirectory.dir("confluentArchive/${baseDir}")
}

tasks.register('createConfluentArchive', Zip) {
    group = "Confluent"
    description = "Creates the Confluent archive file to be released to Confluent Hub"
    dependsOn tasks.prepareConfluentArchive
    from(layout.buildDirectory.dir('confluentArchive'))
    archiveBaseName = ""
    archiveAppendix = archiveFilename
    archiveVersion.set(project.version.toString())
    destinationDirectory = layout.buildDirectory.dir('confluent')
}

tasks.named('build') {
    finalizedBy createConfluentArchive
}
